### ISSUE TITLE
StateDumper AccessDeniedException

### ISSUE THREAD

**Issue by TheAceMan** [BlueMap-Minecraft/BlueMap#573]
### What i did / Steps to reproduce
Upgraded to version 5.2 and an access denied exception on StateDumper.dump, logs below. Running with -w, -u and -r. What folder is the dumper trying to write to so I can verify permissions. Running with -w, -u and -r.

Looks like this line has been removed for the next release. But also wanted to open the bug for anyone having this issue and in case StateDumper is used in the future.

### Expected result
Worked before the upgrade and expect it work after upgrade.

### Actual result
[02:54:52 ERROR] An IO-error occurred!
java.nio.file.AccessDeniedException: teststate.json
        at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(Unknown Source)
        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(Unknown Source)
        at java.base/java.nio.file.Files.newOutputStream(Unknown Source)
        at java.base/java.nio.file.Files.newBufferedWriter(Unknown Source)
        at de.bluecolored.bluemap.common.debug.StateDumper.dump(StateDumper.java:49)
        at de.bluecolored.bluemap.cli.BlueMapCLI.renderMaps(BlueMapCLI.java:215)
        at de.bluecolored.bluemap.cli.BlueMapCLI.main(BlueMapCLI.java:364)

### Context
**BlueMap Version:** 5.2
Running in kubernetes cluster.

```
[02:45:35 INFO] Starting webserver ...
[02:45:35 INFO] Initializing Storage: 'file' (Type: 'bluemap:file')
[02:45:35 INFO] WebServer bound to all network interfaces on port 8100
[02:45:35 INFO] WebServer started.
[02:45:37 INFO] Loading resources...
[02:45:38 INFO] Loading textures...
[02:45:39 INFO] Baking resources...
[02:45:39 INFO] Resources loaded.
[02:45:39 INFO] Loading map 'aaa'...
[02:45:40 INFO] Loading map 'bbb'...
[02:45:41 INFO] Loading map 'ccc'...
[02:45:41 INFO] Loading map 'ddd'...
[02:45:42 INFO] Loading map 'eee'...
[02:45:43 INFO] Loading map 'fff'...
[02:45:43 INFO] Start updating 6 maps (933 regions, ~955392 chunks)...
[02:45:49 INFO] Your maps are now all up-to-date!
[02:45:49 INFO] Waiting for changes on the world-files...
[02:45:49 ERROR] An IO-error occurred!
java.nio.file.AccessDeniedException: teststate.json
        at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(Unknown Source)
        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(Unknown Source)
        at java.base/java.nio.file.Files.newOutputStream(Unknown Source)
        at java.base/java.nio.file.Files.newBufferedWriter(Unknown Source)
        at de.bluecolored.bluemap.common.debug.StateDumper.dump(StateDumper.java:49)
        at de.bluecolored.bluemap.cli.BlueMapCLI.renderMaps(BlueMapCLI.java:215)
        at de.bluecolored.bluemap.cli.BlueMapCLI.main(BlueMapCLI.java:364)
[02:45:49 INFO] Stopping...
[02:45:49 INFO] Saving...
[02:45:49 INFO] Stopped.
```

**Comment by TBlueF** [comment]
> What folder is the dumper trying to write to

The working-directory where you started the `bluemap-cli.jar` in ^^

This was a leftover debug-line i forgot to remove, if there will ever be a real way to create such a dump on the command-line then it will create that file in the `data` folder (configured in the `core.conf`) next to the other files that it creates there anyway already :)

Closing this issue as this is already fixed with b086396

**Comment by TheAceMan** [comment]
@TBlueF 
I see the 5.3 release, but does not appear to be an image tag for the 5.3 release. My container is still failing and a new image would address the above issue. Would like to use a tagged release and not master tag as I check release notes/breaking changes before upgrading.

**Comment by TBlueF** [comment]
@TheAceMan Should be fixed now
